server:
  port: 8024
logging.level.org.springframework.batch: DEBUG 
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB        
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: mysql
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/audictionary?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.audictionary.dto
custom:
  genFileDirPath: ../../vite_projects/audictionary_pd/gen
  logging:
    dir: log
    level: debug